version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: assembly_voting_db
    environment:
      POSTGRES_USER: assembly_user
      POSTGRES_PASSWORD: assembly_pass
      POSTGRES_DB: assembly_voting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assembly_user -d assembly_voting"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
